function [h,status]=basic_info(file,h)
screensize = get( 0, 'Screensize' ); status=0;
fig1=figure('Menubar','none','position',[screensize(3)/2,screensize(4)/3,450,400] ,'visible','off','Name','Basic System Information' ,'NumberTitle','off','CloseRequestFcn', @cancel_button_callback);

%Experiment Name
h.handles.txt2=uicontrol(fig1,'Style','text',...
    'string','Experiment',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0 0.75 0.75],...
    'Position',[5 375 90 20]);
h.handles.Experiment_edit=uicontrol(fig1,'Style', 'edit',...
    'String',' ',...
    'BackgroundColor',[1 1 1],...
    'HandleVisibility','on',...
    'HorizontalAlignment','left',...
    'callback',@Experiment_edit_callback,...
    'Position',[115 375 310 20]);

%Number of channels
h.handles.txt6=uicontrol(fig1,'Style','text',...
    'string','No. of Chans',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0 0.75 0.75],...
    'Position',[5 350 90 20]);
h.handles.channels_edit=uicontrol(fig1,'Style', 'edit',...
    'String',' ',...
    'BackgroundColor',[1 1 1],...
    'HandleVisibility','on',...
    'HorizontalAlignment','left',...
    'callback',@num_channel_edit_callback,...
    'Position',[115 350 310 20]);
 
h.handles.txt2=uicontrol(fig1,'Style','text',...
    'string','Stimulus PC',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0 0.75 0.75],...
    'Position',[5 325 90 20]);
h.handles.stim_pc_edit=uicontrol(fig1,'Style', 'edit',...
    'String','0',...
    'BackgroundColor',[1 1 1],...
    'FontSize',11,...
    'HandleVisibility','on',...
    'HorizontalAlignment','left',...
    'callback',@stim_pc_edit_callback,...
    'Position',[115 325 310 20]);
 
% %data
% h.handles.data =uicontrol(fig1,'Style', 'Pushbutton',...
%     'String','Select',...
%     'HandleVisibility','on',...
%     'callback',@data_dir_button_callback,...
%     'Position',[115 200 50 30]);
% h.handles.txt1=uicontrol(fig1,'Style','text',...
%     'string','System Data Dir',...
%     'HorizontalAlignment','left',...
%     'BackgroundColor',[0 0.75 0.75],...
%     'FontSize',11,...
%     'Position',[5 205 110 20]);
% h.handles.data_edit=uicontrol(fig1,'Style', 'edit',...
%     'String',' ',...
%     'HandleVisibility','on',...
%     'HorizontalAlignment','left',...
%     'BackgroundColor',[1 1 1],...
%     'FontSize',11,...
%     'callback',@data_edit_callback,...
%     'Position',[175 200 250 30]);
%prt
h.handles.prt  =uicontrol(fig1,'Style', 'Pushbutton',...
    'String','Select',...
    'HandleVisibility','on',...
    'callback',@protocol_button_callback,...
    'Position',[115 285 50 30]);
h.handles.txt2=uicontrol(fig1,'Style','text',...
    'string','Protocol Dir',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0 0.75 0.75],...
    'Position',[5 290 85 20]);
h.handles.prt_edit=uicontrol(fig1,'Style', 'edit',...
    'String',' ',...
    'BackgroundColor',[1 1 1],...
    'HandleVisibility','on',...
    'FontSize',11,...
    'HorizontalAlignment','right',...
    'callback',@protocol_edit_callback,...
    'Position',[175 285 250 30]);
%output
h.handles.out  =uicontrol(fig1,'Style', 'Pushbutton',...
    'String','Select',...
    'HandleVisibility','on',...
    'callback',@output_button_callback,...
    'Position',[115 245 50 30]);
h.handles.txt2=uicontrol(fig1,'Style','text',...
    'string','Output Dir',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0 0.75 0.75],...
    'Position',[5 250 75 20]);
h.handles.out_edit=uicontrol(fig1,'Style', 'edit',...
    'String',' ',...
    'BackgroundColor',[1 1 1],...
    'HandleVisibility','on',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'callback',@output_edit_callback,...
    'Position',[175 245 250 30]);
%%%%%
h.handles.auto_se  =uicontrol(fig1,'Style', 'togglebutton',...
    'String','Automatic',...
    'HandleVisibility','on',...
    'callback',@auto_sel_button_callback,...
    'Position',[150 205 100 30]);
h.handles.txt2=uicontrol(fig1,'Style','text',...
    'string','Channel Select',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0 0.75 0.75],...
    'Position',[5 205 100 20]);


%System
h.handles.hitachi  =uicontrol(fig1,'Style', 'Pushbutton',...
    'String','Hitachi',...
    'HandleVisibility','on',...
    'FontSize',9,...
    'callback',@hitachi_button_callback,...
    'Position',[265 160 60 30]);
h.handles.nirx  =uicontrol(fig1,'Style', 'Pushbutton',...
    'String','NIRX',...
    'HandleVisibility','on',...
    'FontSize',9,...
    'callback',@nirx_button_callback,...
    'Position',[165 160 60 30]);
h.handles.txt4=uicontrol(fig1,'Style','text',...
    'string','NIRS system',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0 0.75 0.75],...
    'FontSize',12,...
    'Position',[5 165 100 20]);

%output com
h.handles.txt2=uicontrol(fig1,'Style','text',...
    'string','Output COM',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0 0.75 0.75],...
    'Position',[5 125 90 20]);
h.handles.OutCom_pop=uicontrol(fig1,'Style', 'popup',...
    'String',' ',...
    'BackgroundColor',[1 1 1],...
    'FontSize',11,...
    'HandleVisibility','on',...
    'HorizontalAlignment','left',...
    'enable','off',...
    'callback',@outCOM_popup_callback,...
    'Position',[115 120 310 30]);

%Nirx_address
h.handles.txt2=uicontrol(fig1,'Style','text',...
    'string','COM Address',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0 0.75 0.75],...
    'Position',[5 80 100 20]);
h.handles.OutCom_nirx_edit=uicontrol(fig1,'Style', 'edit',...
    'String',' ',...
    'BackgroundColor',[1 1 1],...
    'FontSize',11,...
    'HandleVisibility','on',...
    'HorizontalAlignment','left',...
    'enable','off',...
    'callback',@outCOM_nirx_edit_callback,...
    'Position',[115 85 310 30]);
% communication
h.handles.txt222=uicontrol(fig1,'Style','text',...
    'string','Communication',...
    'FontSize',11,...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0 0.75 0.75],...
    'Position',[5 50 100 20]);
h.handles.tcp  =uicontrol(fig1,'Style', 'radiobutton',...
    'String','TCP/IP',...
    'HandleVisibility','on',...
    'FontSize',12,...
    'callback',@tcp_button_callback,...
    'Position',[125 50 90 25]);
h.handles.text  =uicontrol(fig1,'Style', 'radiobutton',...
    'String','Text',...
    'HandleVisibility','on',...
    'FontSize',12,...
    'callback',@text_button_callback,...
    'Position',[250 50 90 25]);
% Done
h.handles.done  =uicontrol(fig1,'Style', 'toggle',...
    'String','Cancel',...
    'HandleVisibility','on',...
    'FontSize',12,...
    'callback',@cancel_button_callback,...
    'Position',[125 10 90 30]);
h.handles.done  =uicontrol(fig1,'Style', 'toggle',...
    'String','Done',...
    'HandleVisibility','on',...
    'FontSize',12,...
    'callback',@done_button_callback,...
    'Position',[250 10 90 30]);

if  file==0
    h.basic_info.experiment='';
    h.basic_info.out_com='';
    h.basic_info.isUDP=0;
    h.basic_info.isText=0;
    h.basic_info.stimulus_PC_folder='';
    h.basic_info.auto_sel=0;
    h.basic_info.protocol_dir='';
    h.basic_info.output_dir ='';
    h.basic_info.system='';
    h.basic_info.nirx_address='';h.basic_info.auto_sel=0;
    [~,res]=system('mode');
    aa=regexp(res,'COM\d+','match')';
    h.coms1{1,1}='    ';
    for ii=2:length(aa)
        h.coms1{1,ii+1}=aa{ii};
    end
    set(h.handles.OutCom_pop,'string',h.coms1);
    set(fig1,'visible','on');
elseif ~isempty(file)
    try
        h.old=load(file);
        h.basic_info=h.old.basic_info;
        set(h.handles.stim_pc_edit, 'string',h.basic_info.stimulus_PC_folder);
        set(h.handles.auto_se,'value', h.basic_info.auto_sel);
        set(h.handles.Experiment_edit,'string',h.basic_info.experiment);
        % set(h.handles.data_edit,'string',h.basic_info.system_data_dir);
        set(h.handles.tcp ,'value',h.basic_info.isUDP);
        set(h.handles.text ,'value',h.basic_info.isText);
        if h.basic_info.isUDP
            set(h.handles.tcp,'BackgroundColor',[0,0.5,0])
            set(h.handles.text,'BackgroundColor',[0.94,0.94,0.94])
        elseif h.basic_info.isText
            set(h.handles.tcp,'BackgroundColor',[0.94,0.94,0.94])
            set(h.handles.text,'BackgroundColor',[0,0.5,0])
        end
        set(h.handles.prt_edit,'string',h.basic_info.protocol_dir);
        set(h.handles.out_edit,'string',h.basic_info.output_dir);
        set(h.handles.channels_edit,'string', h.basic_info.num_channel);
        if strcmp(h.basic_info.system,'NIRx')
            set(h.handles.hitachi,'BackgroundColor',[0.94,0.94,0.94])
            set(h.handles.nirx,'BackgroundColor',[0,0.5,0])
            set(h.handles.OutCom_nirx_edit,'string',h.basic_info.nirx_address)
            set(h.handles.OutCom_nirx_edit,'enable','on');
        elseif strcmp(h.basic_info.system,'Hitachi')
            set(h.handles.hitachi,'BackgroundColor',[0,0.5,0])
            set(h.handles.nirx,'BackgroundColor',[0.94,0.94,0.94])
            [~,res]=system('mode');
            aa=regexp(res,'COM\d+','match')';
            for ii=2:size(aa,1)+1
             h.coms1{ii}=aa{ii-1};
                if strcmp(h.basic_info.out_com,aa{ii-1})
                    com_val=ii;
                end
            end
            
            set(h.handles.OutCom_pop,'string',h.coms1);
            set(h.handles.OutCom_pop,'value',com_val);
            %set( h.handles.OutCom_pop,'string',h.basic_info.out_com);
            set(h.handles.OutCom_pop,'enable','on');
        end
        
        set(fig1,'visible','on');
    catch
        [~,res]=system('mode');
        aa=regexp(res,'COM\d+','match')';
        for ii=2:size(aa,1)+1
             h.coms1{ii}=aa{ii-1};
        end
        set(h.handles.OutCom_pop,'string',h.coms1);
        h.basic_info.experiment='';
        h.basic_info.stimulus_PC_folder='';
        h.basic_info.out_com='';
        h.basic_info.num_channel='';
        h.basic_info.protocol_dir='';
        h.basic_info.output_dir ='';
        h.basic_info.system='';
        h.basic_info.nirx_address='';
        h.basic_info.auto_sel=0;
        set(fig1,'visible','on');
    end
end
uiwait(fig1);
    function auto_sel_button_callback(hObject,eventdata,handles)
        if get(hObject,'value')==1
            set(h.handles.auto_se,'BackgroundColor',[0,0.5,0])
            h.basic_info.auto_sel=1;
        else
             set(h.handles.auto_se,'BackgroundColor',[0.94,0.94,0.94])
            h.basic_info.auto_sel=0;
        end
    end
    function Experiment_edit_callback (hObject,eventdata,handles)
        h.basic_info.experiment = strtrim(get(hObject, 'String'));
        
    end
    function outCOM_popup_callback (hObject,eventdata,handles)
        
        h.basic_info.out_com =  h.coms1{get(hObject, 'value')};
        
    end
    function num_channel_edit_callback (hObject,eventdata,handles)
        h.basic_info.num_channel = str2num(strtrim(get(hObject, 'String')));
    end
    function  text_button_callback (hObject,eventdata,handles)
        if get(hObject, 'value')==1
            h.basic_info.isUDP=0;
            h.basic_info.isText=1;
            set(h.handles.tcp,'BackgroundColor',[0.94,0.94,0.94])
            set(h.handles.text,'BackgroundColor',[0,0.5,0])
        else
            h.basic_info.isUDP=1;
            h.basic_info.isText=0;
            set(h.handles.tcp,'BackgroundColor',[0,0.5,0])
            set(h.handles.text,'BackgroundColor',[0.94,0.94,0.94])
        end
    end
    function  tcp_button_callback (hObject,eventdata,handles)
        if get(hObject, 'value')==1
            h.basic_info.isUDP=1;
            h.basic_info.isText=0;
            set(h.handles.tcp,'BackgroundColor',[0,0.5,0])
            set(h.handles.text,'BackgroundColor',[0.94,0.94,0.94])
        else
            h.basic_info.isUDP=0;
            h.basic_info.isText=1;
            set(h.handles.tcp,'BackgroundColor',[0.94,0.94,0.94])
            set(h.handles.text,'BackgroundColor',[0,0.5,0])
        end
    end
    function protocol_button_callback (hObject,eventdata,handles)
        h.basic_info.protocol_dir = uigetdir;
        set(h.handles.prt_edit,'string',h.basic_info.protocol_dir);
    end
    function protocol_edit_callback (hObject,eventdata,handles)
        h.basic_info.protocol_dir = get(hObject, 'String');
        
    end
    function output_button_callback (hObject,eventdata,handles)
        h.basic_info.output_dir = uigetdir;
        set(h.handles.out_edit,'string',h.basic_info.output_dir);
    end
    function output_edit_callback (hObject,eventdata,handles)
        h.basic_info.output_dir = get(hObject, 'String');
    end

    function nirx_button_callback(hObject,eventdata,handles)
        if (get(hObject, 'Value') == 1)||(get(hObject, 'Value') == 1)
            set(h.handles.nirx,'BackgroundColor',[0,0.5,0])
            set(h.handles.hitachi,'BackgroundColor',[0.94,0.94,0.94])
            set(h.handles.OutCom_nirx_edit, 'enable','on')
            h.basic_info.system='NIRx';
        end
    end
    function hitachi_button_callback(hObject,eventdata,handles)
        if (get(hObject, 'Value') == 1)||(get(hObject, 'Value') == 1)
            set(h.handles.hitachi,'BackgroundColor',[0,0.5,0])
            set(h.handles.nirx,'BackgroundColor',[0.94,0.94,0.94])
            set( h.handles.OutCom_pop, 'enable','on');
            h.basic_info.system='Hitachi';
        end
    end
    function stim_pc_edit_callback(hObject,eventdata,handles)
         h.basic_info.stimulus_PC_folder= strtrim(get(hObject, 'String'));
    end
    function outCOM_nirx_edit_callback(hObject,eventdata,handles)
        h.basic_info.nirx_address=hex2dec(strtrim(get(hObject, 'String')));
    end
    function done_button_callback(hObject,eventdata,handles)
        if ~isempty(h.basic_info.system)&& ~isempty( h.basic_info.experiment)&& ~isempty(h.basic_info.num_channel) && (~isempty( h.basic_info.out_com) ||~isempty(h.basic_info.nirx_address))&& ~isempty( h.basic_info.protocol_dir) &&~isempty( ~isempty(h.basic_info.output_dir))
            
            basic_info=h.basic_info;
            if ~isdeployed
                
                if exist([fileparts(which('pradeep.m')), filesep,'basic_info'],'dir')~=7
                    mkdir( [fileparts(which('pradeep.m')), filesep,'basic_info']);
                end
                save([fileparts(which('nirs_feedback.m')), filesep,'basic_info',filesep,'basic_info_', h.basic_info.experiment,'.mat'],'basic_info'); status=1;
                
            else
                [status,result]=system('path');
                root_path=char(regexp(result,'Path=(.*?);','tokens','once'));
                if exist([root_path, filesep,'basic_info'],'dir')~=7
                    mkdir( [root_path, filesep,'basic_info']);
                end
                save([root_path, filesep,'basic_info',filesep,'basic_info_', h.basic_info.experiment,'.mat'],'basic_info'); status=1;
                
            end
            delete(gcf);
            return
        end
    end
    function cancel_button_callback(hObject,eventdata,handles)
        status=0;
        delete(gcf);
        return
        
    end

end