function [chn_str ]= input_channel(condition,bci)
screensize = get( 0, 'Screensize' );chn_str={''};
% fig1=figure('position',[screensize(3)/2,screensize(4)/2,450, 200] ,'visible','on','Name','Basic System Information' ,'NumberTitle','off');
if strcmp(condition,'correlation')
    %Experiment Name
    fig1=figure('position',[screensize(3)/2,screensize(4)/2,450, 250] ,'visible','on','Name','Channel Info correlation' ,'NumberTitle','off');
    h.handles.txt2=uicontrol(fig1,'Style','text',...
        'string','Channels Selected',...
        'FontSize',11,...
        'HorizontalAlignment','left',...
        'BackgroundColor',[0.84 0.84 0.84],...
        'Position',[155 220 130 20]);
    h.handles.Experiment_edit=uicontrol(fig1,'Style', 'text',...
        'String',' ',...
        'BackgroundColor',[0.9 0.9 0.9],...
        'FontSize',11,...
        'HandleVisibility','on',...
        'HorizontalAlignment','left',...
        'Position',[65 190 320 25]);
    
    %Number of channels
    h.handles.txt6=uicontrol(fig1,'Style','text',...
        'string', 'Channels for ROI 1',...
        'FontSize',11,...
        'HorizontalAlignment','left',...
        'BackgroundColor',[0.84 0.84 0.84],...
        'Position',[155 155 130 20]);
    h.handles.ch_roi1_edit=uicontrol(fig1,'Style', 'edit',...
        'String',' ',...
        'BackgroundColor',[ 1 1  1],...
        'HandleVisibility','on',...
        'HorizontalAlignment','left',...
        'FontSize',11,...
        'callback',@ch_roi1_edit_callback,...
        'Position',[65 120 320 25]);
    
    %output Com
    h.handles.txt2=uicontrol(fig1,'Style','text',...
        'string','Channels for ROI 2',...
        'FontSize',11,...
        'HorizontalAlignment','left',...
        'BackgroundColor',[0.84 0.84 0.84],...
        'Position',[155  90 130 20]);
    h.handles.ch_roi2_edit=uicontrol(fig1,'Style', 'edit',...
        'String',' ',...
        'BackgroundColor',[1 1 1],...
        'FontSize',11,...
        'HandleVisibility','on',...
        'HorizontalAlignment','left',...
        'callback',@ch_roi2_edit_callback,...
        'Position',[65  60 320 25]);
    
    %    Done
    
    h.handles.done  =uicontrol(fig1,'Style', 'toggle',...
        'String','Done',...
        'HandleVisibility','on',...
        'FontSize',12,...
        'callback',@done_button_callback,...
        'Position',[185 10 60 30]);
elseif strcmp(condition,'normal')
    fig1=figure('position',[screensize(3)/2,screensize(4)/2,450, 180] ,'visible','on','Name','Channel Information' ,'NumberTitle','off');
    
    h.handles.txt2=uicontrol(fig1,'Style','text',...
        'string','Channels Selected',...
        'FontSize',11,...
        'HorizontalAlignment','left',...
        'BackgroundColor',[0.84 0.84 0.84],...
        'Position',[155 160 130 20]);
    h.handles.Experiment_edit=uicontrol(fig1,'Style', 'text',...
        'String',' ',...
        'BackgroundColor',[0.90 0.90 0.90],...
        'FontSize',11,...
        'HandleVisibility','on',...
        'HorizontalAlignment','left',...
        'Position',[65 130 320 25]);
    
    %Number of channels
    h.handles.txt8=uicontrol(fig1,'Style','text',...
        'string', 'Channels for ROI',...
        'FontSize',11,...
        'HorizontalAlignment','left',...
        'BackgroundColor',[0.84 0.84 0.84],...
        'Position',[155 90 125 20]);
    h.handles.ch_sel_edit=uicontrol(fig1,'Style', 'edit',...
        'String',' ',...
        'BackgroundColor',[1 1 1],...
        'HandleVisibility','on',...
        'FontSize',11,...
        'HorizontalAlignment','left',...
        'callback',@ch_sel_edit_callback,...
        'Position',[65 60 320 25]);
    
    %    Done
    
    h.handles.done  =uicontrol(fig1,'Style', 'toggle',...
        'String','Done',...
        'HandleVisibility','on',...
        'FontSize',12,...
        'callback',@done_button_callback,...
        'Position',[175 10 60 30]);
    
    
end
if isfield(bci,'fsel')
set(h.handles.Experiment_edit,'string',num2str(bci.fsel));
else
    set(h.handles.Experiment_edit,'string','');
end
uiwait(fig1);
    function ch_roi2_edit_callback (hObject,eventdata,handles)
        h.roi{1,2}= get(hObject, 'String');
        
    end
    function ch_roi1_edit_callback (hObject,eventdata,handles)
        h.roi{1,1} = get(hObject, 'String');
        
    end
    function ch_sel_edit_callback (hObject,eventdata,handles)
        h.roi_single{1,1} = get(hObject, 'String');
    end
    function done_button_callback(hObject,eventdata,handles)
        if strcmp(condition,'correlation')
             if  ~isempty(h.roi{1,1}) && ~isempty(h.roi{1,2})
                 chn_str=h.roi;
                 delete(gcf)
             end
        elseif strcmp(condition,'normal')
            if  ~isempty(h.roi_single{1,1})  
                 chn_str=h.roi_single{1};
                 delete(gcf)
            end
        end
        
    end
end